# -*- mode: python ; coding: utf-8 -*-
import sys
sys.setrecursionlimit(5000)

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'bleak',
        'bleak.backends.winrt',
        'bleak.backends.winrt.client',
        'pyqtgraph',
        'pyqtgraph.graphicsitems',
        'pyqtgraph.graphicsitems.PlotItem',
        'pyqtgraph.graphicsitems.PlotDataItem',
        'pyqtgraph.graphicsitems.ScatterPlotItem',
        'pyqtgraph.graphicsitems.AxisItem',
        'pyqtgraph.graphicsitems.ViewBox',
        'pyqtgraph.graphicsitems.GridItem',
        'pyqtgraph.graphicsitems.LinearRegionItem',
        'pyqtgraph.graphicsItems',
        'pyqtgraph.graphicsItems.PlotItem',
        'pyqtgraph.graphicsItems.PlotDataItem',
        'pyqtgraph.graphicsItems.ScatterPlotItem',
        'pyqtgraph.graphicsItems.AxisItem',
        'pyqtgraph.graphicsItems.ViewBox',
        'pyqtgraph.graphicsItems.GridItem',
        'pyqtgraph.graphicsItems.LinearRegionItem',
        'numpy',
        'numpy.core',
        'numpy.core._multiarray_umath',
        'openpyxl',
        'openpyxl.cell',
        'openpyxl.chart',
        'openpyxl.worksheet',
        'themes',
        'mini_heart_widget',
        'ble_scanner_dialog',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='HeartRateMonitor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)